gui:
  main-menu-title: "<gradient:blue:aqua><bold>ChatColor"
  color-selector-title: "<aqua><bold>Solid Colors"
  gradient-selector-title: "<gradient:red:blue><bold>Gradients"
  pattern-selector-title: "<rainbow><bold>Patterns"

settings:
  apply-to-message: true
  apply-to-name: false
  default-color: "NONE"
  event-priority: "LOWEST"
  papi-integration: true
  late-bind: false
